# Generated by Django 4.2.24 on 2025-09-22 07:14

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0003_project_avatar_project_project_status_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstimateCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Название категории"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Код категории"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="projects.estimatecategory",
                        verbose_name="Родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория сметных работ",
                "verbose_name_plural": "Категории сметных работ",
                "db_table": "estimate_categories",
                "ordering": ["code", "name"],
            },
        ),
        migrations.CreateModel(
            name="EstimateRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Код расценки"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=500, verbose_name="Название работы"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Базовая цена",
                    ),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Стоимость труда",
                    ),
                ),
                (
                    "material_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Стоимость материалов",
                    ),
                ),
                (
                    "equipment_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Стоимость оборудования",
                    ),
                ),
                (
                    "labor_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="Трудозатраты (часы)",
                    ),
                ),
                (
                    "complexity_factor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=3,
                        verbose_name="Коэффициент сложности",
                    ),
                ),
                (
                    "region_factor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=3,
                        verbose_name="Региональный коэффициент",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="projects.estimatecategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расценка",
                "verbose_name_plural": "Расценки",
                "db_table": "estimate_rates",
                "ordering": ["code", "name"],
            },
        ),
        migrations.CreateModel(
            name="EstimateTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название шаблона"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Публичный"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="projects.estimatecategory",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон сметы",
                "verbose_name_plural": "Шаблоны смет",
                "db_table": "estimate_templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EstimateUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Краткое название"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Единица измерения",
                "verbose_name_plural": "Единицы измерения",
                "db_table": "estimate_units",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="projectestimate",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата утверждения"
            ),
        ),
        migrations.AddField(
            model_name="projectestimate",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_estimates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Утвердил",
            ),
        ),
        migrations.AddField(
            model_name="projectestimate",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="projectestimate",
            name="equipment_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Стоимость оборудования",
            ),
        ),
        migrations.AddField(
            model_name="projectestimate",
            name="estimate_type",
            field=models.CharField(
                choices=[
                    ("simple", "Простая смета"),
                    ("detailed", "Детализированная смета"),
                    ("template", "Смета по шаблону"),
                    ("imported", "Импортированная смета"),
                ],
                default="simple",
                max_length=20,
                verbose_name="Тип сметы",
            ),
        ),
        migrations.AddField(
            model_name="projectestimate",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Утверждена"),
        ),
        migrations.AddField(
            model_name="projectestimate",
            name="labor_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Стоимость труда",
            ),
        ),
        migrations.AddField(
            model_name="projectestimate",
            name="material_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Стоимость материалов",
            ),
        ),
        migrations.AddField(
            model_name="projectestimate",
            name="name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Название сметы"
            ),
        ),
        migrations.AddField(
            model_name="projectestimate",
            name="overhead_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15.00"),
                max_digits=5,
                verbose_name="Накладные расходы (%)",
            ),
        ),
        migrations.AddField(
            model_name="projectestimate",
            name="profit_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                max_digits=5,
                verbose_name="Прибыль (%)",
            ),
        ),
        migrations.AddField(
            model_name="projectestimate",
            name="region_factor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                max_digits=3,
                verbose_name="Региональный коэффициент",
            ),
        ),
        migrations.AddField(
            model_name="projectestimate",
            name="version",
            field=models.PositiveIntegerField(default=1, verbose_name="Версия"),
        ),
        migrations.CreateModel(
            name="ProjectEstimateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Цена за единицу",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Общая стоимость",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="Позиция"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "region_factor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=3,
                        verbose_name="Региональный коэффициент",
                    ),
                ),
                (
                    "complexity_factor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=3,
                        verbose_name="Коэффициент сложности",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "estimate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="projects.projectestimate",
                        verbose_name="Смета",
                    ),
                ),
                (
                    "rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimate_items",
                        to="projects.estimaterate",
                        verbose_name="Расценка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция сметы",
                "verbose_name_plural": "Позиции сметы",
                "db_table": "project_estimate_items",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="EstimateTemplateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="Позиция"),
                ),
                (
                    "rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_items",
                        to="projects.estimaterate",
                        verbose_name="Расценка",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="projects.estimatetemplate",
                        verbose_name="Шаблон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция шаблона",
                "verbose_name_plural": "Позиции шаблона",
                "db_table": "estimate_template_items",
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="estimaterate",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates",
                to="projects.estimateunit",
                verbose_name="Единица измерения",
            ),
        ),
        migrations.CreateModel(
            name="EstimateImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("excel", "Excel файл"),
                            ("grand_smeta", "ГрандСмета"),
                            ("smeta_ru", "Смета.ру"),
                            ("rik", "РИК"),
                            ("arps", "АРПС"),
                            ("other", "Другое"),
                        ],
                        default="excel",
                        max_length=20,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Имя файла"),
                ),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="Путь к файлу"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("processing", "Обрабатывается"),
                            ("completed", "Завершен"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "imported_items",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Импортировано позиций"
                    ),
                ),
                ("errors", models.TextField(blank=True, verbose_name="Ошибки")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершен"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimate_imports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Импортировал",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimate_imports",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Импорт сметы",
                "verbose_name_plural": "Импорты смет",
                "db_table": "estimate_imports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EstimateExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("excel", "Excel файл"),
                            ("pdf", "PDF документ"),
                            ("word", "Word документ"),
                            ("xml", "XML файл"),
                            ("json", "JSON файл"),
                        ],
                        default="excel",
                        max_length=20,
                        verbose_name="Формат",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Имя файла"),
                ),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="Путь к файлу"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("processing", "Обрабатывается"),
                            ("completed", "Завершен"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершен"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimate_exports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Экспортировал",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimate_exports",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Экспорт сметы",
                "verbose_name_plural": "Экспорты смет",
                "db_table": "estimate_exports",
                "ordering": ["-created_at"],
            },
        ),
    ]
