# Generated by Django 5.2.6 on 2025-09-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_estimateunit_projectestimate_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Фото объекта для проекта', null=True, upload_to='project_avatars/', verbose_name='Аватарка проекта'),
        ),
    ]
