# Generated by Django 4.2.24 on 2025-09-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_estimateunit_projectestimate_approved_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Фото объекта для проекта",
                null=True,
                upload_to="project_avatars/",
                verbose_name="Аватарка проекта",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status"], name="project_status_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["created_by"], name="project_created_by_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["is_active"], name="project_active_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["created_at"], name="project_created_at_idx"),
        ),
    ]
