# Generated by Django 4.2.24 on 2025-09-21 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_estimateunit_projectestimate_approved_at_and_more"),
        ("projects", "0004_project_avatar"),
    ]

    operations = []
