version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: superpan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/superpan
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  telegram_bot:
    build: .
    command: python run_telegram_bot.py
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/superpan
    depends_on:
      - db
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
