# Generated by Django 5.2.6 on 2025-09-10 08:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_project_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Категория склада',
                'verbose_name_plural': 'Категории склада',
                'db_table': 'warehouse_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('item_type', models.CharField(choices=[('MATERIAL', 'Материал'), ('EQUIPMENT', 'Оборудование')], max_length=20, verbose_name='Тип товара')),
                ('unit', models.CharField(default='шт', max_length=20, verbose_name='Единица измерения')),
                ('current_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Текущее количество')),
                ('min_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Минимальное количество')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена закупки')),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена продажи')),
                ('equipment_photo_before', models.ImageField(blank=True, null=True, upload_to='warehouse/equipment/before/', verbose_name='Фото оборудования до начала работ')),
                ('equipment_photo_after', models.ImageField(blank=True, null=True, upload_to='warehouse/equipment/after/', verbose_name='Фото оборудования после завершения работ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='warehouse.warehousecategory', verbose_name='Категория')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warehouse_items', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Товар склада',
                'verbose_name_plural': 'Товары склада',
                'db_table': 'warehouse_items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Количество использовано')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала использования')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания использования')),
                ('condition_before', models.TextField(blank=True, verbose_name='Состояние до использования')),
                ('condition_after', models.TextField(blank=True, verbose_name='Состояние после использования')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_equipment', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='projects.project', verbose_name='Проект')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_usage', to='warehouse.warehouseitem', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Оборудование проекта',
                'verbose_name_plural': 'Оборудование проектов',
                'db_table': 'project_equipment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Приход'), ('OUT', 'Расход'), ('TRANSFER', 'Перемещение'), ('ADJUSTMENT', 'Корректировка')], max_length=20, verbose_name='Тип операции')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Общая сумма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Номер документа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warehouse_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='warehouse.warehouseitem', verbose_name='Товар')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_transactions', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Транзакция склада',
                'verbose_name_plural': 'Транзакции склада',
                'db_table': 'warehouse_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
