# Generated by Django 5.2.6 on 2025-09-03 14:19

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(default='#007bff', help_text='HEX код цвета', max_length=7, verbose_name='Цвет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Категория расходов',
                'verbose_name_plural': 'Категории расходов',
                'db_table': 'expense_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('expense_type', models.CharField(choices=[('material', 'Материалы'), ('labor', 'Работы'), ('transport', 'Транспорт'), ('fuel', 'Топливо'), ('equipment', 'Оборудование'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Тип расхода')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_review', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('paid', 'Оплачено')], default='pending', max_length=20, verbose_name='Статус')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция в колонке')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата одобрения')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expense_items', to=settings.AUTH_USER_MODEL, verbose_name='Одобрил')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_expense_items', to=settings.AUTH_USER_MODEL, verbose_name='Назначен')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_items', to='kanban.expensecategory', verbose_name='Категория')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_expense_items', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Элемент расхода',
                'verbose_name_plural': 'Элементы расходов',
                'db_table': 'expense_items',
                'ordering': ['column__position', 'position', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Действие')),
                ('old_value', models.TextField(blank=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, verbose_name='Новое значение')),
                ('field_name', models.CharField(blank=True, max_length=50, verbose_name='Поле')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('expense_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='kanban.expenseitem', verbose_name='Элемент расхода')),
            ],
            options={
                'verbose_name': 'История изменений расхода',
                'verbose_name_plural': 'История изменений расходов',
                'db_table': 'expense_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='expense_documents/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('receipt', 'Чек'), ('invoice', 'Счет'), ('contract', 'Договор'), ('photo', 'Фотография'), ('other', 'Другое')], default='receipt', max_length=20, verbose_name='Тип документа')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_expense_documents', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
                ('expense_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kanban.expenseitem', verbose_name='Элемент расхода')),
            ],
            options={
                'verbose_name': 'Документ расхода',
                'verbose_name_plural': 'Документы расходов',
                'db_table': 'expense_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('is_internal', models.BooleanField(default=False, verbose_name='Внутренний комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('expense_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kanban.expenseitem', verbose_name='Элемент расхода')),
            ],
            options={
                'verbose_name': 'Комментарий к расходу',
                'verbose_name_plural': 'Комментарии к расходам',
                'db_table': 'expense_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KanbanBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_boards', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_board', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Канбан-доска',
                'verbose_name_plural': 'Канбан-доски',
                'db_table': 'kanban_boards',
            },
        ),
        migrations.CreateModel(
            name='KanbanColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название колонки')),
                ('column_type', models.CharField(choices=[('pending', 'Ожидает'), ('in_review', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('paid', 'Оплачено')], default='pending', max_length=20, verbose_name='Тип колонки')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('color', models.CharField(default='#f8f9fa', max_length=7, verbose_name='Цвет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='kanban.kanbanboard', verbose_name='Доска')),
            ],
            options={
                'verbose_name': 'Колонка канбан-доски',
                'verbose_name_plural': 'Колонки канбан-доски',
                'db_table': 'kanban_columns',
                'ordering': ['position'],
                'unique_together': {('board', 'position')},
            },
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kanban.kanbancolumn', verbose_name='Колонка'),
        ),
    ]
