# Generated by Django 5.2.6 on 2025-09-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='photo_files',
            field=models.FileField(blank=True, help_text='Загрузите фотографии (можно несколько файлов)', null=True, upload_to='expense_photos/', verbose_name='Фотографии'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='receipt_file',
            field=models.FileField(blank=True, help_text='Загрузите чек, счет или другой документ', null=True, upload_to='expense_receipts/', verbose_name='Чек/Счет'),
        ),
    ]
