# Generated by Django 5.2.6 on 2025-09-09 09:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_taskcategory_taskpriority_taskstatus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecomment',
            options={'ordering': ['created_at'], 'verbose_name': 'Комментарий к задаче', 'verbose_name_plural': 'Комментарии к задачам'},
        ),
        migrations.AlterModelOptions(
            name='expenseitem',
            options={'ordering': ['column__position', 'position', '-created_at'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RemoveField(
            model_name='expenseitem',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='expenseitem',
            name='expense_type',
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Планируемые часы'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='Срочная'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='progress_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Прогресс (%)'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='tags',
            field=models.CharField(blank=True, help_text='Через запятую', max_length=500, verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='task_type',
            field=models.CharField(choices=[('purchase', 'Закупка'), ('work', 'Работа'), ('delivery', 'Поставка'), ('installation', 'Монтаж'), ('control', 'Контроль'), ('documentation', 'Документация'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='expensecomment',
            name='expense_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kanban.expenseitem', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('todo', 'К выполнению'), ('in_progress', 'В работе'), ('review', 'На проверке'), ('done', 'Выполнена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
