# Generated by Django 5.2.6 on 2025-09-09 10:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_alter_expensecomment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Сумма'),
        ),
    ]
