# Generated by Django 5.2.6 on 2025-09-11 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_expenseitem_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Цвет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Этап строительства',
                'verbose_name_plural': 'Этапы строительства',
                'db_table': 'construction_stages',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='task_type',
            field=models.CharField(choices=[('purchase', 'Закупка'), ('work', 'Работа'), ('delivery', 'Поставка'), ('installation', 'Монтаж'), ('control', 'Контроль'), ('documentation', 'Документация'), ('message', 'Сообщение'), ('photo_report', 'Фотоотчет'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Тип задачи'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='kanban.constructionstage', verbose_name='Этап строительства'),
        ),
    ]
