# Generated by Django 5.2.6 on 2025-09-16 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_constructionstage_alter_expenseitem_task_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCommentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Загрузите фото, видео или документ', upload_to='task_comments/attachments/', verbose_name='Файл')),
                ('file_name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер файла')),
                ('file_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('document', 'Документ'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Тип файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='kanban.expensecomment', verbose_name='Комментарий')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_comment_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Вложение к комментарию',
                'verbose_name_plural': 'Вложения к комментариям',
                'db_table': 'expense_comment_attachments',
                'ordering': ['-created_at'],
            },
        ),
    ]
