# Generated by Django 5.2.6 on 2025-09-16 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0007_expensecommentattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('new', 'Новая'), ('todo', 'К выполнению'), ('in_progress', 'В работе'), ('review', 'На проверке'), ('done', 'Выполнена'), ('cancelled', 'Отменена')], max_length=20, verbose_name='Старый статус')),
                ('new_status', models.CharField(choices=[('new', 'Новая'), ('todo', 'К выполнению'), ('in_progress', 'В работе'), ('review', 'На проверке'), ('done', 'Выполнена'), ('cancelled', 'Отменена')], max_length=20, verbose_name='Новый статус')),
                ('reason', models.TextField(blank=True, verbose_name='Причина изменения')),
                ('status', models.CharField(choices=[('pending', 'Ожидает утверждения'), ('approved', 'Утверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус запроса')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Утвердил')),
                ('expense_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_change_requests', to='kanban.expenseitem', verbose_name='Задача')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Запросил')),
            ],
            options={
                'verbose_name': 'Запрос на изменение статуса',
                'verbose_name_plural': 'Запросы на изменение статуса',
                'db_table': 'status_change_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
