# Generated by Django 5.2.6 on 2025-09-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectaccesskey',
            name='description',
            field=models.TextField(blank=True, help_text='Описание цели предоставления доступа', verbose_name='Описание'),
        ),
    ]
