# Generated by Django 5.2.6 on 2025-09-04 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_projectaccesskey_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectaccesskey',
            unique_together=set(),
        ),
    ]
