# Generated by Django 5.2.6 on 2025-09-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('chief_engineer', 'Главный инженер'), ('foreman', 'Прораб'), ('warehouse_keeper', 'Кладовщик'), ('supplier', 'Снабженец'), ('contractor', 'Подрядчик')], default='contractor', max_length=20, verbose_name='Роль'),
        ),
    ]
