# Generated by Django 5.2.6 on 2025-09-11 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(help_text='Уникальный ID пользователя в Telegram', unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, help_text='@username в Telegram', max_length=100, verbose_name='Telegram Username')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя в Telegram')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия в Telegram')),
                ('language_code', models.CharField(default='ru', max_length=10, verbose_name='Код языка')),
                ('is_bot', models.BooleanField(default=False, verbose_name='Это бот')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Telegram Premium')),
                ('photo_url', models.URLField(blank=True, verbose_name='URL фото профиля')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Telegram профиль',
                'verbose_name_plural': 'Telegram профили',
                'db_table': 'telegram_users',
            },
        ),
    ]
