# Generated by Django 5.2.6 on 2025-09-11 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_telegramuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAuthToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, help_text='Уникальный токен для авторизации', primary_key=True, serialize=False, verbose_name='Токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(help_text='Время истечения токена', verbose_name='Истекает')),
                ('is_used', models.BooleanField(default=False, help_text='Был ли токен использован для авторизации', verbose_name='Использован')),
                ('telegram_user', models.ForeignKey(blank=True, help_text='Telegram пользователь, который авторизовался', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.telegramuser', verbose_name='Telegram пользователь')),
                ('user', models.ForeignKey(blank=True, help_text='Пользователь, который авторизовался через этот токен', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Токен авторизации Telegram',
                'verbose_name_plural': 'Токены авторизации Telegram',
                'db_table': 'telegram_auth_tokens',
            },
        ),
    ]
