# Generated by Django 5.2.6 on 2025-09-16 07:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_email'),
        ('kanban', '0006_constructionstage_alter_expenseitem_task_type_and_more'),
        ('projects', '0004_project_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор-суперпользователь'), ('chief_engineer', 'Главный инженер'), ('foreman', 'Прораб'), ('warehouse_keeper', 'Кладовщик'), ('supplier', 'Снабженец'), ('economist', 'Экономист/Начальник коммерческого отдела'), ('contractor', 'Подрядчик')], default='contractor', max_length=20, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('project_status', 'Изменение статуса проекта'), ('task_confirmation', 'Подтверждение задачи'), ('budget_change', 'Изменение бюджета'), ('warehouse_item', 'Изменение товара склада'), ('equipment_photo', 'Фото оборудования')], max_length=20, verbose_name='Тип запроса')),
                ('status', models.CharField(choices=[('pending', 'Ожидает одобрения'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус')),
                ('description', models.TextField(verbose_name='Описание изменений')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='Старые данные')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='Новые данные')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Одобрен')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='Одобрил')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='projects.project', verbose_name='Проект')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Запросил')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='kanban.projecttask', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Запрос на одобрение',
                'verbose_name_plural': 'Запросы на одобрение',
                'db_table': 'approval_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(max_length=200, verbose_name='Название оборудования')),
                ('photo_type', models.CharField(choices=[('before', 'До'), ('after', 'После')], max_length=10, verbose_name='Тип фото')),
                ('photo', models.ImageField(upload_to='equipment_photos/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_photos', to='projects.project', verbose_name='Проект')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_equipment_photos', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Фото оборудования',
                'verbose_name_plural': 'Фото оборудования',
                'db_table': 'equipment_photos',
                'ordering': ['-created_at'],
            },
        ),
    ]
