# Generated by Django 5.2.6 on 2025-09-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_role_approvalrequest_equipmentphoto'),
    ]

    operations = [
    ]
